import type { Job } from "./types";

/**
 * Demo dataset used for development and for live demos when no real job
 * sources are configured. These are fictional listings created in-house for
 * this application — they are NOT scraped from any job board.
 *
 * When a licensed provider is added (see JobSource in types.ts), this dataset
 * remains the development fallback so the Discover page is never empty.
 */

const daysAgo = (n: number) => {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
};

export const DEMO_JOBS: Job[] = [
  {
    id: "demo-senior-frontend",
    title: "Senior Frontend Engineer",
    company: "Nimbus Cloud",
    companyId: "demo-nimbus",
    companyLogo: "",
    companyDescription:
      "Nimbus Cloud builds developer-friendly infrastructure for the next generation of web apps.",
    location: "Remote · Worldwide",
    workType: "remote",
    type: "full-time",
    experienceLevel: "senior",
    experience: "5+ years",
    salary: "$140k – $180k",
    salaryMin: 140000,
    salaryMax: 180000,
    skills: ["React", "TypeScript", "Next.js", "GraphQL", "Testing", "Performance"],
    description:
      "Own the frontend architecture of our core product. You'll build design systems, improve performance, and mentor a small team of engineers. Strong TypeScript and React skills required, plus experience shipping large-scale applications.",
    postedAt: daysAgo(2),
    source: "demo",
  },
  {
    id: "demo-backend-node",
    title: "Backend Engineer (Node.js)",
    company: "Dataforge",
    companyId: "demo-dataforge",
    companyLogo: "",
    companyDescription:
      "Dataforge processes billions of events per day for the world's leading analytics teams.",
    location: "Remote · US Timezones",
    workType: "remote",
    type: "full-time",
    experienceLevel: "mid",
    experience: "3+ years",
    salary: "$120k – $155k",
    salaryMin: 120000,
    salaryMax: 155000,
    skills: ["Node.js", "TypeScript", "PostgreSQL", "Redis", "AWS", "Microservices"],
    description:
      "Design and build high-throughput APIs that power our real-time analytics platform. Experience with Node.js, PostgreSQL, and event-driven architectures is essential.",
    postedAt: daysAgo(1),
    source: "demo",
  },
  {
    id: "demo-fullstack",
    title: "Full Stack Developer",
    company: "Launchpad",
    companyId: "demo-launchpad",
    companyLogo: "",
    companyDescription:
      "Launchpad helps early-stage startups validate ideas faster with a suite of product tools.",
    location: "Hybrid · Bengaluru, India",
    workType: "hybrid",
    type: "full-time",
    experienceLevel: "mid",
    experience: "2–4 years",
    salary: "₹18L – ₹30L",
    salaryMin: 50000,
    salaryMax: 85000,
    skills: ["React", "Node.js", "MongoDB", "Tailwind CSS", "REST APIs", "Docker"],
    description:
      "Join a fast-moving product team shipping customer-facing features weekly. You'll work across the stack — React frontends, Node APIs, and our MongoDB data layer.",
    postedAt: daysAgo(3),
    source: "demo",
  },
  {
    id: "demo-ml-engineer",
    title: "Machine Learning Engineer",
    company: "Cognitiva AI",
    companyId: "demo-cognitiva",
    companyLogo: "",
    companyDescription:
      "Cognitiva AI builds applied machine learning products for enterprise customers.",
    location: "Onsite · San Francisco, CA",
    workType: "onsite",
    type: "full-time",
    experienceLevel: "senior",
    experience: "4+ years",
    salary: "$170k – $220k",
    salaryMin: 170000,
    salaryMax: 220000,
    skills: ["Python", "PyTorch", "TensorFlow", "LLMs", "MLOps", "Kubernetes"],
    description:
      "Productionize LLM-powered features across our product suite. You'll train, fine-tune, and deploy models at scale with a strong focus on evaluation and reliability.",
    postedAt: daysAgo(5),
    source: "demo",
  },
  {
    id: "demo-frontend-intern",
    title: "Frontend Engineering Intern",
    company: "Launchpad",
    companyId: "demo-launchpad",
    companyLogo: "",
    companyDescription:
      "Launchpad helps early-stage startups validate ideas faster with a suite of product tools.",
    location: "Remote · India",
    workType: "remote",
    type: "internship",
    experienceLevel: "internship",
    experience: "0–1 years",
    salary: "₹25k – ₹40k / month",
    salaryMin: 8000,
    salaryMax: 15000,
    skills: ["React", "JavaScript", "CSS", "HTML", "Git"],
    description:
      "A 6-month paid internship with real product ownership. Work alongside senior engineers on our design system and customer-facing features. Freshers with strong fundamentals encouraged to apply.",
    postedAt: daysAgo(1),
    source: "demo",
  },
  {
    id: "demo-junior-swe",
    title: "Junior Software Engineer",
    company: "Peakline",
    companyId: "demo-peakline",
    companyLogo: "",
    companyDescription: "Peakline is a customer support platform used by 4,000+ teams worldwide.",
    location: "Hybrid · Gurugram, India",
    workType: "hybrid",
    type: "full-time",
    experienceLevel: "fresher",
    experience: "0–2 years",
    salary: "₹8L – ₹14L",
    salaryMin: 22000,
    salaryMax: 40000,
    skills: ["JavaScript", "React", "Node.js", "SQL", "Git", "Problem Solving"],
    description:
      "Perfect first role for a motivated fresher. You'll fix bugs, ship small features, and learn from senior engineers on a friendly, collaborative team. Clear growth path to mid-level.",
    postedAt: daysAgo(4),
    source: "demo",
  },
  {
    id: "demo-devops",
    title: "DevOps / SRE Engineer",
    company: "Orbital Systems",
    companyId: "demo-orbital",
    companyLogo: "",
    companyDescription:
      "Orbital Systems runs mission-critical infrastructure for fintech and healthcare customers.",
    location: "Remote · EMEA",
    workType: "remote",
    type: "full-time",
    experienceLevel: "senior",
    experience: "5+ years",
    salary: "$130k – $165k",
    salaryMin: 130000,
    salaryMax: 165000,
    skills: ["AWS", "Terraform", "Kubernetes", "CI/CD", "Observability", "Linux"],
    description:
      "Own our cloud infrastructure and release pipelines. Improve reliability through automation, monitoring, and incident response. Strong Terraform and AWS experience required.",
    postedAt: daysAgo(6),
    source: "demo",
  },
  {
    id: "demo-ux-designer",
    title: "Product Designer (UX/UI)",
    company: "Palette",
    companyId: "demo-palette",
    companyLogo: "",
    companyDescription:
      "Palette makes beautiful design accessible to every team, from startups to enterprises.",
    location: "Hybrid · New York, NY",
    workType: "hybrid",
    type: "full-time",
    experienceLevel: "mid",
    experience: "3+ years",
    salary: "$110k – $145k",
    salaryMin: 110000,
    salaryMax: 145000,
    skills: ["Figma", "UX Research", "Prototyping", "Design Systems", "User Testing"],
    description:
      "Lead design for our collaboration features. You'll run user research, create prototypes, and partner with product and engineering to ship polished experiences.",
    postedAt: daysAgo(7),
    source: "demo",
  },
  {
    id: "demo-data-analyst",
    title: "Data Analyst",
    company: "Meridian Finance",
    companyId: "demo-meridian",
    companyLogo: "",
    companyDescription:
      "Meridian Finance is a modern digital bank focused on transparent, fair financial products.",
    location: "Remote · Worldwide",
    workType: "remote",
    type: "full-time",
    experienceLevel: "mid",
    experience: "2+ years",
    salary: "$90k – $120k",
    salaryMin: 90000,
    salaryMax: 120000,
    skills: ["SQL", "Python", "Tableau", "Excel", "Statistics", "Data Visualization"],
    description:
      "Turn raw product and financial data into insights that drive decisions. Build dashboards, run experiments, and partner with growth and product teams.",
    postedAt: daysAgo(2),
    source: "demo",
  },
  {
    id: "demo-mobile",
    title: "Mobile Engineer (React Native)",
    company: "Wander",
    companyId: "demo-wander",
    companyLogo: "",
    companyDescription:
      "Wander is a travel planning app used by millions of explorers across 60+ countries.",
    location: "Hybrid · Berlin, Germany",
    workType: "hybrid",
    type: "full-time",
    experienceLevel: "mid",
    experience: "3+ years",
    salary: "€75k – €95k",
    salaryMin: 85000,
    salaryMax: 110000,
    skills: ["React Native", "TypeScript", "iOS", "Android", "GraphQL", "Mobile UX"],
    description:
      "Build delightful mobile experiences used by millions. You'll own features end-to-end across iOS and Android using React Native and TypeScript.",
    postedAt: daysAgo(3),
    source: "demo",
  },
  {
    id: "demo-security",
    title: "Security Engineer",
    company: "Shieldnet",
    companyId: "demo-shieldnet",
    companyLogo: "",
    companyDescription:
      "Shieldnet provides security monitoring trusted by governments and enterprises alike.",
    location: "Remote · US",
    workType: "remote",
    type: "full-time",
    experienceLevel: "senior",
    experience: "5+ years",
    salary: "$150k – $195k",
    salaryMin: 150000,
    salaryMax: 195000,
    skills: [
      "Application Security",
      "Cloud Security",
      "Penetration Testing",
      "OWASP",
      "AWS",
      "Python",
    ],
    description:
      "Embed with product teams to secure our platform. Conduct threat modeling, lead pen tests, and build security tooling. Cloud and appsec experience essential.",
    postedAt: daysAgo(8),
    source: "demo",
  },
  {
    id: "demo-qa",
    title: "QA Automation Engineer",
    company: "Testify",
    companyId: "demo-testify",
    companyLogo: "",
    companyDescription:
      "Testify is an AI-powered testing platform that helps teams ship with confidence.",
    location: "Onsite · Pune, India",
    workType: "onsite",
    type: "full-time",
    experienceLevel: "junior",
    experience: "1–3 years",
    salary: "₹8L – ₹16L",
    salaryMin: 22000,
    salaryMax: 44000,
    skills: ["Playwright", "Cypress", "JavaScript", "API Testing", "CI/CD", "Test Automation"],
    description:
      "Build and maintain automated test suites across web and API surfaces. Work closely with developers to shift quality left. Playwright experience a big plus.",
    postedAt: daysAgo(2),
    source: "demo",
  },
  {
    id: "demo-pm",
    title: "Product Manager",
    company: "Northwind",
    companyId: "demo-northwind",
    companyLogo: "",
    companyDescription:
      "Northwind builds workflow automation for operations teams at Fortune 500 companies.",
    location: "Hybrid · London, UK",
    workType: "hybrid",
    type: "full-time",
    experienceLevel: "mid",
    experience: "3+ years",
    salary: "£70k – £95k",
    salaryMin: 90000,
    salaryMax: 120000,
    skills: [
      "Product Strategy",
      "Roadmapping",
      "User Research",
      "Agile",
      "Analytics",
      "Stakeholder Management",
    ],
    description:
      "Own the roadmap for our flagship workflow builder. Talk to customers weekly, define requirements, and ship measurable outcomes with a cross-functional team.",
    postedAt: daysAgo(4),
    source: "demo",
  },
  {
    id: "demo-backend-java",
    title: "Backend Engineer (Java/Kotlin)",
    company: "Ledgerline",
    companyId: "demo-ledgerline",
    companyLogo: "",
    companyDescription:
      "Ledgerline builds accounting infrastructure that powers modern fintech companies.",
    location: "Remote · APAC",
    workType: "remote",
    type: "full-time",
    experienceLevel: "senior",
    experience: "4+ years",
    salary: "$135k – $170k",
    salaryMin: 135000,
    salaryMax: 170000,
    skills: ["Java", "Kotlin", "Spring Boot", "Kafka", "PostgreSQL", "Distributed Systems"],
    description:
      "Design resilient, distributed backend services for a ledger platform handling millions of transactions. Deep Java/Kotlin and event-streaming experience expected.",
    postedAt: daysAgo(1),
    source: "demo",
  },
];
