/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAiUsageRouteImport } from './routes/admin.ai-usage'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminCompaniesRouteImport } from './routes/admin.companies'
import { Route as AdminJobsRouteImport } from './routes/admin.jobs'
import { Route as AdminMonitoringRouteImport } from './routes/admin.monitoring'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as CompanyIndexRouteImport } from './routes/company.index'
import { Route as CompanyAnalyticsRouteImport } from './routes/company.analytics'
import { Route as CompanyApplicantsRouteImport } from './routes/company.applicants'
import { Route as CompanyInterviewRouteImport } from './routes/company.interview'
import { Route as CompanyJobsRouteImport } from './routes/company.jobs'
import { Route as CompanyNotificationsRouteImport } from './routes/company.notifications'
import { Route as CompanySettingsRouteImport } from './routes/company.settings'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAnalyzerRouteImport } from './routes/dashboard.analyzer'
import { Route as DashboardApplicationsRouteImport } from './routes/dashboard.applications'
import { Route as DashboardAtsRouteImport } from './routes/dashboard.ats'
import { Route as DashboardBillingRouteImport } from './routes/dashboard.billing'
import { Route as DashboardBuilderRouteImport } from './routes/dashboard.builder'
import { Route as DashboardCoverLetterRouteImport } from './routes/dashboard.cover-letter'
import { Route as DashboardDiscoverRouteImport } from './routes/dashboard.discover'
import { Route as DashboardImportRouteImport } from './routes/dashboard.import'
import { Route as DashboardJobMatchRouteImport } from './routes/dashboard.job-match'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardOptimizerRouteImport } from './routes/dashboard.optimizer'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardRoadmapRouteImport } from './routes/dashboard.roadmap'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardSkillGapRouteImport } from './routes/dashboard.skill-gap'
import { Route as DashboardTemplatesRouteImport } from './routes/dashboard.templates'
import { Route as DashboardVersionsRouteImport } from './routes/dashboard.versions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiUsageRoute = AdminAiUsageRouteImport.update({
  id: '/ai-usage',
  path: '/ai-usage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCompaniesRoute = AdminCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMonitoringRoute = AdminMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const CompanyIndexRoute = CompanyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyAnalyticsRoute = CompanyAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyApplicantsRoute = CompanyApplicantsRouteImport.update({
  id: '/applicants',
  path: '/applicants',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyInterviewRoute = CompanyInterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyJobsRoute = CompanyJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyNotificationsRoute = CompanyNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanySettingsRoute = CompanySettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CompanyRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyzerRoute = DashboardAnalyzerRouteImport.update({
  id: '/analyzer',
  path: '/analyzer',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApplicationsRoute = DashboardApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAtsRoute = DashboardAtsRouteImport.update({
  id: '/ats',
  path: '/ats',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBuilderRoute = DashboardBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCoverLetterRoute = DashboardCoverLetterRouteImport.update({
  id: '/cover-letter',
  path: '/cover-letter',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDiscoverRoute = DashboardDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardImportRoute = DashboardImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJobMatchRoute = DashboardJobMatchRouteImport.update({
  id: '/job-match',
  path: '/job-match',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOptimizerRoute = DashboardOptimizerRouteImport.update({
  id: '/optimizer',
  path: '/optimizer',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRoadmapRoute = DashboardRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSkillGapRoute = DashboardSkillGapRouteImport.update({
  id: '/skill-gap',
  path: '/skill-gap',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTemplatesRoute = DashboardTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVersionsRoute = DashboardVersionsRouteImport.update({
  id: '/versions',
  path: '/versions',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/company': typeof CompanyRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/ai-usage': typeof AdminAiUsageRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/company/analytics': typeof CompanyAnalyticsRoute
  '/company/applicants': typeof CompanyApplicantsRoute
  '/company/interview': typeof CompanyInterviewRoute
  '/company/jobs': typeof CompanyJobsRoute
  '/company/notifications': typeof CompanyNotificationsRoute
  '/company/settings': typeof CompanySettingsRoute
  '/dashboard/analyzer': typeof DashboardAnalyzerRoute
  '/dashboard/applications': typeof DashboardApplicationsRoute
  '/dashboard/ats': typeof DashboardAtsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/builder': typeof DashboardBuilderRoute
  '/dashboard/cover-letter': typeof DashboardCoverLetterRoute
  '/dashboard/discover': typeof DashboardDiscoverRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/dashboard/job-match': typeof DashboardJobMatchRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/optimizer': typeof DashboardOptimizerRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/roadmap': typeof DashboardRoadmapRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/skill-gap': typeof DashboardSkillGapRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/dashboard/versions': typeof DashboardVersionsRoute
  '/admin/': typeof AdminIndexRoute
  '/company/': typeof CompanyIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/ai-usage': typeof AdminAiUsageRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/company/analytics': typeof CompanyAnalyticsRoute
  '/company/applicants': typeof CompanyApplicantsRoute
  '/company/interview': typeof CompanyInterviewRoute
  '/company/jobs': typeof CompanyJobsRoute
  '/company/notifications': typeof CompanyNotificationsRoute
  '/company/settings': typeof CompanySettingsRoute
  '/dashboard/analyzer': typeof DashboardAnalyzerRoute
  '/dashboard/applications': typeof DashboardApplicationsRoute
  '/dashboard/ats': typeof DashboardAtsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/builder': typeof DashboardBuilderRoute
  '/dashboard/cover-letter': typeof DashboardCoverLetterRoute
  '/dashboard/discover': typeof DashboardDiscoverRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/dashboard/job-match': typeof DashboardJobMatchRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/optimizer': typeof DashboardOptimizerRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/roadmap': typeof DashboardRoadmapRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/skill-gap': typeof DashboardSkillGapRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/dashboard/versions': typeof DashboardVersionsRoute
  '/admin': typeof AdminIndexRoute
  '/company': typeof CompanyIndexRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/company': typeof CompanyRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/ai-usage': typeof AdminAiUsageRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/company/analytics': typeof CompanyAnalyticsRoute
  '/company/applicants': typeof CompanyApplicantsRoute
  '/company/interview': typeof CompanyInterviewRoute
  '/company/jobs': typeof CompanyJobsRoute
  '/company/notifications': typeof CompanyNotificationsRoute
  '/company/settings': typeof CompanySettingsRoute
  '/dashboard/analyzer': typeof DashboardAnalyzerRoute
  '/dashboard/applications': typeof DashboardApplicationsRoute
  '/dashboard/ats': typeof DashboardAtsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/builder': typeof DashboardBuilderRoute
  '/dashboard/cover-letter': typeof DashboardCoverLetterRoute
  '/dashboard/discover': typeof DashboardDiscoverRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/dashboard/job-match': typeof DashboardJobMatchRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/optimizer': typeof DashboardOptimizerRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/roadmap': typeof DashboardRoadmapRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/skill-gap': typeof DashboardSkillGapRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/dashboard/versions': typeof DashboardVersionsRoute
  '/admin/': typeof AdminIndexRoute
  '/company/': typeof CompanyIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/company'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/admin/ai-usage'
    | '/admin/analytics'
    | '/admin/companies'
    | '/admin/jobs'
    | '/admin/monitoring'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/company/analytics'
    | '/company/applicants'
    | '/company/interview'
    | '/company/jobs'
    | '/company/notifications'
    | '/company/settings'
    | '/dashboard/analyzer'
    | '/dashboard/applications'
    | '/dashboard/ats'
    | '/dashboard/billing'
    | '/dashboard/builder'
    | '/dashboard/cover-letter'
    | '/dashboard/discover'
    | '/dashboard/import'
    | '/dashboard/job-match'
    | '/dashboard/notifications'
    | '/dashboard/optimizer'
    | '/dashboard/profile'
    | '/dashboard/roadmap'
    | '/dashboard/settings'
    | '/dashboard/skill-gap'
    | '/dashboard/templates'
    | '/dashboard/versions'
    | '/admin/'
    | '/company/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/admin/ai-usage'
    | '/admin/analytics'
    | '/admin/companies'
    | '/admin/jobs'
    | '/admin/monitoring'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/company/analytics'
    | '/company/applicants'
    | '/company/interview'
    | '/company/jobs'
    | '/company/notifications'
    | '/company/settings'
    | '/dashboard/analyzer'
    | '/dashboard/applications'
    | '/dashboard/ats'
    | '/dashboard/billing'
    | '/dashboard/builder'
    | '/dashboard/cover-letter'
    | '/dashboard/discover'
    | '/dashboard/import'
    | '/dashboard/job-match'
    | '/dashboard/notifications'
    | '/dashboard/optimizer'
    | '/dashboard/profile'
    | '/dashboard/roadmap'
    | '/dashboard/settings'
    | '/dashboard/skill-gap'
    | '/dashboard/templates'
    | '/dashboard/versions'
    | '/admin'
    | '/company'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/company'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/admin/ai-usage'
    | '/admin/analytics'
    | '/admin/companies'
    | '/admin/jobs'
    | '/admin/monitoring'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/company/analytics'
    | '/company/applicants'
    | '/company/interview'
    | '/company/jobs'
    | '/company/notifications'
    | '/company/settings'
    | '/dashboard/analyzer'
    | '/dashboard/applications'
    | '/dashboard/ats'
    | '/dashboard/billing'
    | '/dashboard/builder'
    | '/dashboard/cover-letter'
    | '/dashboard/discover'
    | '/dashboard/import'
    | '/dashboard/job-match'
    | '/dashboard/notifications'
    | '/dashboard/optimizer'
    | '/dashboard/profile'
    | '/dashboard/roadmap'
    | '/dashboard/settings'
    | '/dashboard/skill-gap'
    | '/dashboard/templates'
    | '/dashboard/versions'
    | '/admin/'
    | '/company/'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CompanyRoute: typeof CompanyRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-usage': {
      id: '/admin/ai-usage'
      path: '/ai-usage'
      fullPath: '/admin/ai-usage'
      preLoaderRoute: typeof AdminAiUsageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/companies': {
      id: '/admin/companies'
      path: '/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AdminCompaniesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/monitoring': {
      id: '/admin/monitoring'
      path: '/monitoring'
      fullPath: '/admin/monitoring'
      preLoaderRoute: typeof AdminMonitoringRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/company/': {
      id: '/company/'
      path: '/'
      fullPath: '/company/'
      preLoaderRoute: typeof CompanyIndexRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/company/analytics': {
      id: '/company/analytics'
      path: '/analytics'
      fullPath: '/company/analytics'
      preLoaderRoute: typeof CompanyAnalyticsRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/company/applicants': {
      id: '/company/applicants'
      path: '/applicants'
      fullPath: '/company/applicants'
      preLoaderRoute: typeof CompanyApplicantsRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/company/interview': {
      id: '/company/interview'
      path: '/interview'
      fullPath: '/company/interview'
      preLoaderRoute: typeof CompanyInterviewRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/company/jobs': {
      id: '/company/jobs'
      path: '/jobs'
      fullPath: '/company/jobs'
      preLoaderRoute: typeof CompanyJobsRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/company/notifications': {
      id: '/company/notifications'
      path: '/notifications'
      fullPath: '/company/notifications'
      preLoaderRoute: typeof CompanyNotificationsRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/company/settings': {
      id: '/company/settings'
      path: '/settings'
      fullPath: '/company/settings'
      preLoaderRoute: typeof CompanySettingsRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analyzer': {
      id: '/dashboard/analyzer'
      path: '/analyzer'
      fullPath: '/dashboard/analyzer'
      preLoaderRoute: typeof DashboardAnalyzerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/applications': {
      id: '/dashboard/applications'
      path: '/applications'
      fullPath: '/dashboard/applications'
      preLoaderRoute: typeof DashboardApplicationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ats': {
      id: '/dashboard/ats'
      path: '/ats'
      fullPath: '/dashboard/ats'
      preLoaderRoute: typeof DashboardAtsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/builder': {
      id: '/dashboard/builder'
      path: '/builder'
      fullPath: '/dashboard/builder'
      preLoaderRoute: typeof DashboardBuilderRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cover-letter': {
      id: '/dashboard/cover-letter'
      path: '/cover-letter'
      fullPath: '/dashboard/cover-letter'
      preLoaderRoute: typeof DashboardCoverLetterRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/discover': {
      id: '/dashboard/discover'
      path: '/discover'
      fullPath: '/dashboard/discover'
      preLoaderRoute: typeof DashboardDiscoverRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/import': {
      id: '/dashboard/import'
      path: '/import'
      fullPath: '/dashboard/import'
      preLoaderRoute: typeof DashboardImportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/job-match': {
      id: '/dashboard/job-match'
      path: '/job-match'
      fullPath: '/dashboard/job-match'
      preLoaderRoute: typeof DashboardJobMatchRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/optimizer': {
      id: '/dashboard/optimizer'
      path: '/optimizer'
      fullPath: '/dashboard/optimizer'
      preLoaderRoute: typeof DashboardOptimizerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/roadmap': {
      id: '/dashboard/roadmap'
      path: '/roadmap'
      fullPath: '/dashboard/roadmap'
      preLoaderRoute: typeof DashboardRoadmapRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/skill-gap': {
      id: '/dashboard/skill-gap'
      path: '/skill-gap'
      fullPath: '/dashboard/skill-gap'
      preLoaderRoute: typeof DashboardSkillGapRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/templates': {
      id: '/dashboard/templates'
      path: '/templates'
      fullPath: '/dashboard/templates'
      preLoaderRoute: typeof DashboardTemplatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/versions': {
      id: '/dashboard/versions'
      path: '/versions'
      fullPath: '/dashboard/versions'
      preLoaderRoute: typeof DashboardVersionsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAiUsageRoute: typeof AdminAiUsageRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCompaniesRoute: typeof AdminCompaniesRoute
  AdminJobsRoute: typeof AdminJobsRoute
  AdminMonitoringRoute: typeof AdminMonitoringRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiUsageRoute: AdminAiUsageRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCompaniesRoute: AdminCompaniesRoute,
  AdminJobsRoute: AdminJobsRoute,
  AdminMonitoringRoute: AdminMonitoringRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CompanyRouteChildren {
  CompanyAnalyticsRoute: typeof CompanyAnalyticsRoute
  CompanyApplicantsRoute: typeof CompanyApplicantsRoute
  CompanyInterviewRoute: typeof CompanyInterviewRoute
  CompanyJobsRoute: typeof CompanyJobsRoute
  CompanyNotificationsRoute: typeof CompanyNotificationsRoute
  CompanySettingsRoute: typeof CompanySettingsRoute
  CompanyIndexRoute: typeof CompanyIndexRoute
}

const CompanyRouteChildren: CompanyRouteChildren = {
  CompanyAnalyticsRoute: CompanyAnalyticsRoute,
  CompanyApplicantsRoute: CompanyApplicantsRoute,
  CompanyInterviewRoute: CompanyInterviewRoute,
  CompanyJobsRoute: CompanyJobsRoute,
  CompanyNotificationsRoute: CompanyNotificationsRoute,
  CompanySettingsRoute: CompanySettingsRoute,
  CompanyIndexRoute: CompanyIndexRoute,
}

const CompanyRouteWithChildren =
  CompanyRoute._addFileChildren(CompanyRouteChildren)

interface DashboardRouteChildren {
  DashboardAnalyzerRoute: typeof DashboardAnalyzerRoute
  DashboardApplicationsRoute: typeof DashboardApplicationsRoute
  DashboardAtsRoute: typeof DashboardAtsRoute
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardBuilderRoute: typeof DashboardBuilderRoute
  DashboardCoverLetterRoute: typeof DashboardCoverLetterRoute
  DashboardDiscoverRoute: typeof DashboardDiscoverRoute
  DashboardImportRoute: typeof DashboardImportRoute
  DashboardJobMatchRoute: typeof DashboardJobMatchRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardOptimizerRoute: typeof DashboardOptimizerRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardRoadmapRoute: typeof DashboardRoadmapRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSkillGapRoute: typeof DashboardSkillGapRoute
  DashboardTemplatesRoute: typeof DashboardTemplatesRoute
  DashboardVersionsRoute: typeof DashboardVersionsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyzerRoute: DashboardAnalyzerRoute,
  DashboardApplicationsRoute: DashboardApplicationsRoute,
  DashboardAtsRoute: DashboardAtsRoute,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardBuilderRoute: DashboardBuilderRoute,
  DashboardCoverLetterRoute: DashboardCoverLetterRoute,
  DashboardDiscoverRoute: DashboardDiscoverRoute,
  DashboardImportRoute: DashboardImportRoute,
  DashboardJobMatchRoute: DashboardJobMatchRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardOptimizerRoute: DashboardOptimizerRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardRoadmapRoute: DashboardRoadmapRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSkillGapRoute: DashboardSkillGapRoute,
  DashboardTemplatesRoute: DashboardTemplatesRoute,
  DashboardVersionsRoute: DashboardVersionsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CompanyRoute: CompanyRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
